### ISSUE TITLE
builds, but fails to run

### ISSUE THREAD

**Issue by alexmyczko** [splotchviz/splotch#2]
$ splotch

+---------+
| splotch |
+---------+

Vector math: SSE
OpenMP active, but running with 1 thread only.
MPI active, but running with 1 task only.

Usage: splotch \<parameter file\>
terminate called after throwing an instance of 'PlanckError'
zsh: abort      splotch

full build logs availabe at:
http://sid.ethz.ch/debian/splotch/

**Comment by TimDykes** [comment]
Hi Alex, 

You need to pass a parameter file to Splotch, for some reason the 'usage' output is incorrect - it should say 'Usage: splotch \<parameter file\>". I'll create a bug to fix that.

You can see more on usage of Splotch on the [wiki](https://github.com/splotchviz/splotch/wiki), an example dataset & parameter file is available in data/snap092.tgz

Hope this helps, 

Tim

**Comment by TimDykes** [comment]
On second look, the usage message is correct, it just didnt display in your comment because the angle brackets werent escaped with a slash. I updated your comment to add these in.

In any case, you should use Splotch in this way:

./splotch parameter_file.par

**Comment by alexmyczko** [comment]
looks a bit better, seems i have to update paths in the source, for splotch to find palette/ in maybe /usr/share/splotch/palette/

but then it has this fixed path somewhere:
could not open input file! </Users/tims/Data/SNAP_092/snap_092>

./snap092.par:infile=/Users/tims/Data/SNAP_092/snap_

works after updating the .par file path

**Comment by TimDykes** [comment]
Hi Alex, 

You can simply edit the infile parameter by opening snap092.par in vim or other text editor (it is just a text file) to modify the path for your system, likewise if you have moved splotch from the default build directory you should also update the palette paths in the parameter file (palette0, palette1) to prefix the global path to your splotch repository.

Let me know if you get stuck.

Cheers,

Tim

**Comment by alexmyczko** [comment]
Thanks a lot. I guess that all works. I'll prepare a debian package for this, if it makes sense. Does it still get developped further?

**Comment by alexmyczko** [comment]
Great. The only missing things are a much better long description for the software (2-3 lines). And a manual page, I have a started one you might want to add to the project, and improve?

http://sid.ethz.ch/debian/splotch/repack/splotch-0.1%2Bgit20171004/debian/
see splotch.1

**Comment by TimDykes** [comment]
Hi Alex,

Thanks a lot for this, apologies I didnt reply to the previous message - yes, Splotch is still under further development (we have a private git repository that we merge into the public version).

I will look into testing this out with a view to including it in the project.

Cheers,

Tim

**Comment by alexmyczko** [comment]
Hi Tim,

When will the merge happen?

Cheers,

**Comment by TimDykes** [comment]
Hi Alex,

Sorry for the delayed response, I have been away for a while. There is a large update to Splotch that will be merged, however it will likely not happen for another 2-3 months.

Thanks,

Tim

**Comment by alexmyczko** [comment]
Any updates on this?

**Comment by TimDykes** [comment]
Still working on the update at the moment, its a fairly significant new codebase (adds interactive and web streaming features), and I am also working to finish my phd thesis so it may take some time to merge it into the public repository. 

If you are particularly interested in the new features for some project you're welcome to try out the private version

**Comment by alexmyczko** [comment]
Where could I find the private version for a short try?

**Comment by TimDykes** [comment]
Hi Alex,

Apologies for the delayed response.

The private version still has a somewhat complex build procedure, but if you are interested to try it then please email me directly at tim.dykes (at) port.ac.uk and we can work through setting it up.

Thanks,

Tim

**Comment by alexmyczko** [comment]
I heard some interest from the debian astronomy team to have splotch, Debian will have a new release freeze mid Jan 2019. So if you are able to update this github repo with your private version and simply the build procedure that'd be great news...

**Comment by TimDykes** [comment]
Hi Alex, 

Apologies for not replying, we have been inactive in the public repository for some time now. 

I am in the process of updating this repository and cleaning up some things, so if you are still interested in getting this software in Debian I'd be happy to talk more. Im closing this issue as it was originally for a build problem. Feel free to open a new issue re. debian inclusion if interested and we can talk more.

Cheers,

Tim
